# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    target-branch: "develop"
    directory: "/source"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "docker"
    target-branch: "develop"
    directory: "/source/AAS.TwinEngine.DataEngine"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
